# -*- coding: utf-8 -*-
"""Linear Regression Deployment on streamLit .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X1VJGfFofHO5mMV-ohidfL3mrN_Jj8a
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LogisticRegression

# -----------------------------------
# Page Configuration
# -----------------------------------
st.set_page_config(
    page_title="Insurance Sales Prediction",
    page_icon="🏠",
    layout="centered"
)

st.title("Insurance Sales Prediction")
st.write("Insurance Data Set Logistic Regression")

# -----------------------------------
# Load Dataset
# -----------------------------------
df = pd.read_csv("insurance_data.csv")

st.subheader("Insurance Dataset")
st.dataframe(df)

# -----------------------------------
# Train Model
# -----------------------------------
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age']],df.bought_insurance,train_size=0.8)
model = LogisticRegression()
model.fit(X_train, y_train)

# -----------------------------------
# User Input
# -----------------------------------
st.subheader("Enter Age of Person")

age = st.number_input(
    "Age (in Years)",
    min_value=10,
    max_value=65,
    value=18,
    step=1
)

# -----------------------------------
# Prediction
# -----------------------------------
if st.button("Predict Insurance in Yes/No"):
    # Now 'age' is guaranteed to exist and fall between 10 and 65
    prediction = model.predict([[age]])
    
    # Display the result
    if prediction[0] == 1:
        st.success("Result: Yes, likely to buy insurance.")
    else:
        st.info("Result: No, unlikely to buy insurance.")

   

# -----------------------------------
# Model Information
# -----------------------------------
